config/routes.rb
Borcly::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :transactions do
      collection do
        get 'paid'
        get 'overdue'
        get 'broadcast'
        get 'check'
      end
    end

    match 'accounts' => 'accounts#index', :as => :accounts
    match 'accounts/update' => 'accounts#update', :as => :update_account, :via => :post
    root :to =>  'transactions#index'
  end

  root :to => 'home#index'
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::BaseController

  def index
    @user = current_user
  end

  def update
    current_user.email = params[:email]
    current_user.first_time = false
    current_user.save!
    redirect_to admin_root_path, :notice => "Hesap Ayarlariniz Guncellendi" and return
  end
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/admin/accounts/index.html.erb
<div class="row">
  <div class="span8">
    <%= form_tag admin_update_account_path, :class => "form-horizontal" do %>
    <fieldset>
      <legend>Üyelik Bilgilerinizi Güncelleyin</legend>
      <div class="control-group">
        <label for="focusedInput" class="control-label">E-Posta:</label>

        <div class="controls">
          <%= text_field_tag 'email', current_user.email, :class => 'input-xlarge' %>
        </div>
      </div>

      <% current_user.channels.each do |channel| %>
          <div class="control-group">
            <label class="control-label"><%= channel.provider %></label>
          </div>
      <% end %>

      <%= link_to 'Facebook', user_omniauth_authorize_path(:facebook) %>
      <%= link_to 'Twitter', user_omniauth_authorize_path(:twitter) %>

    </fieldset>

    <div class="modal-footer">
      <%= submit_tag "Guncelleyin", :class => 'btn btn-primary' %>
    </div>

    <% end %>
  </div>
</div>