config/routes.rb
Borcly::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :transactions do
      collection do
        get 'paid'
        get 'overdue'
        get 'broadcast'
        get 'check'
      end
    end

    match 'accounts' => 'accounts#index', :as => :accounts
    match 'accounts/update' => 'accounts#update', :as => :update_account, :via => :post
    root :to =>  'transactions#index'
  end

  root :to => 'home#index'
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::BaseController

  def index
    @transactions = current_user.transactions.not_paid.order(:start_date).page params[:page]
  end

  def paid
    @transactions = current_user.transactions.paid.order(:start_date).page params[:page]
  end

  def overdue
    @transactions = current_user.transactions.overdue.order(:start_date).page params[:page]
  end

  def new
    @transaction = Transaction.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def create
    @transaction = Transaction.new(params[:transaction])
    @transaction.user = current_user
    @transaction.status = :not_paid.to_s

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to admin_transactions_url, notice: 'Yeni Borc Kaydi olusturuldu' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @transaction = current_user.transactions.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html {
          status = ''
          status = "#{@transaction.status}_" unless @transaction.status == 'not_paid'
          redirect_to eval("#{status}admin_transactions_path"),
                      notice: 'Borc Kaydi guncellendi'
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction = current_user.transactions.find(params[:id])
    status = ''
    status = "#{@transaction.status}_" unless @transaction.status == 'not_paid'
    @transaction.destroy

    respond_to do |format|
      redirect_to eval("#{status}admin_transactions_path"), notice: 'Borc Silindi' and return
      format.json { head :no_content }
    end
  end


  def broadcast
    @transaction = current_user.transactions.find(params[:id])

    respond_to do |format|
      if @transaction.broadcast()
        format.html { redirect_to overdue_admin_transactions_url, notice: 'Sosyal aglarinizda borclu duyurusu yapildi' }
      else
        format.html { redirect_to overdue_admin_transactions_url, error: 'Sosyal baglantilarinizda sorun yasandi' }
      end
    end
  end

  #check user's debit history
  def check
    email = params[:email]
    result = !Transaction.user_credited_before_and_not_paid?(email).nil?
    render :text =>  result.to_s
  end

end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/views/admin/transactions/_form.html.erb
<%= form_for([:admin, @transaction], :html => {:class => "form-horizontal #{'check-paid' if params[:action] == 'new'}" }) do |f| %>
    <fieldset>
      <div class="control-group">
        <label for="related_person_name" class="control-label">Borc Verilen Adi:</label>

        <div class="controls">
          <%= f.text_field :related_person_name, :class => 'input-xlarge' %>
        </div>
      </div>

      <div class="control-group">
        <label for="related_person_email" class="control-label">Borc Verilen E-Posta:</label>

        <div class="controls">
          <%= f.text_field :related_person_email, :class => 'input-xlarge' %>
        </div>
      </div>

      <% if params[:action] == 'edit' %>

          <div class="control-group">
            <label for="type" class="control-label">Borc Durumu:</label>

            <div class="controls">
              <%= f.select(:status, Transaction::STATUS.collect { |key, value| [value, key] }) %>
            </div>
          </div>

      <% end %>
      <div class="control-group">
        <label for="amount" class="control-label">Borc Miktari:</label>

        <div class="controls">
          <%= f.text_field :amount, :class => 'input-xlarge' %>
        </div>
      </div>

      <div class="control-group">
        <label for="amount" class="control-label">Borclu Twitter Hesabi:</label>

        <div class="controls">
          <%= f.text_field :related_person_twitter, :class => 'input-xlarge' %>
        </div>
      </div>

      <div class="control-group">
        <label for="amount" class="control-label">Borclu Facebook Hesabi:</label>

        <div class="controls">
          <%= f.text_field :related_person_facebook, :class => 'input-xlarge' %>
        </div>
      </div>

      <div class="control-group">
        <label for="start_date" class="control-label">Borc Verme Tarihi:</label>

        <div class="controls">
          <%= f.date_select :start_date, :class => 'input-xlarge' %>
        </div>
      </div>

      <div class="control-group">
        <label for="end_date" class="control-label">Borc Vade Son Tarihi:</label>

        <div class="controls">
          <%= f.date_select :end_date, :class => 'input-xlarge' %>
        </div>
      </div>

      <div class="modal-footer">
        <%= f.submit :class => 'btn btn-primary' %>
        <%= link_to 'Geri', '#' , :class => 'btn back-button'%>
      </div>

    </fieldset>
<% end %>

app/views/admin/transactions/_list.html.erb
<div class="btn-toolbar">
  <div class="btn-group">
    <a href="#" class="btn"><i class="icon-align-left"></i></a>
    <a href="#" class="btn"><i class="icon-align-center"></i></a>
    <a href="#" class="btn"><i class="icon-align-right"></i></a>
    <a href="#" class="btn"><i class="icon-align-justify"></i></a>
  </div>
</div>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th><input type="checkbox"/></th>
    <th class="yellow">Borclu Adi</th>
    <th class="yellow">Borclu Email</th>
    <th class="blue">Miktar</th>
    <th class="green">Verilme Tarihi</th>
    <th class="green">Vade Tarihi</th>
    <th class="green">Durum</th>
    <th class="green"></th>
  </tr>
  </thead>
  <tbody>

  <% @transactions.each do |transaction| %>
      <tr>
        <td><input type="checkbox"/></td>
        <td><%= transaction.related_person_name %></td>
        <td><%= transaction.related_person_email %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.start_date %></td>
        <td><%= transaction.end_date %></td>
        <td><%= Transaction::STATUS[transaction.status.to_sym] %></td>
        <td>
          <div class="btn-group">
            <%= link_to raw('<i class="icon-cog"></i>'), edit_admin_transaction_path(:id => transaction.id), :class => 'btn', :title => 'Duzenle' %>
            <%= link_to raw('<i class="icon-trash icon-white"></i>'), admin_transaction_path(:id => transaction.id),
                        :method => :delete, :confirm => 'Emin misiniz?', :class => "btn btn-danger"%>
            <% if params[:action] == 'overdue' %>
                <%= link_to raw('<i class="icon-share"></i>'), broadcast_admin_transactions_path(:id => transaction.id), :class => 'btn', :title => 'Yayinla' %>
            <% end %>
          </div>
        </td>
      </tr>
  <% end %>

  </tbody>
</table>

<%= paginate @transactions %>

app/views/admin/transactions/edit.html.erb
<div class="row">
  <div class="span2">
    <%= render 'admin/shared/sidebar' %>
  </div>
  <div class="span9">

    <div class="page-header">
      <h1>Borc Kaydinizi Duzenleyin </h1>
    </div>
    <%= render 'form' %>
  </div>

</div>

app/views/admin/transactions/index.html.erb
<div class="row">
  <div class="span2">
    <%= render 'admin/shared/sidebar' %>
  </div>
  <div class="span9">

    <div class="page-header">
      <h1>Alacaklarim </h1>
    </div>

    <%= render 'admin/transactions/list' %>
  </div>

</div>

app/views/admin/transactions/new.html.erb
<div class="row">
  <div class="span2">
    <%= render 'admin/shared/sidebar' %>
  </div>
  <div class="span9">

    <div class="page-header">
      <h1>Yeni Borc Kaydi</h1>
    </div>
    <%= render 'form' %>
  </div>

</div>

app/views/admin/transactions/overdue.html.erb
<div class="row">
  <div class="span2">
    <%= render 'admin/shared/sidebar' %>
  </div>
  <div class="span9">

    <div class="page-header">
      <h1>Vadesi Gecmis Borclariniz</h1>
    </div>

    <%= render 'admin/transactions/list' %>
  </div>

</div>

app/views/admin/transactions/paid.html.erb
<%= content_for(:search) do %>
    <form action="" class="navbar-search pull-left">
      <input type="text" placeholder="Ara" class="search-query span2">
    </form>
<% end %>

<div class="row">
  <div class="span2">
    <%= render 'admin/shared/sidebar' %>
  </div>
  <div class="span9">

    <div class="page-header">
      <h1>Odenmis Borclariniz</h1>
    </div>

    <%= render 'admin/transactions/list' %>
  </div>

</div>