config/routes.rb
Borcly::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :transactions do
      collection do
        get 'paid'
        get 'overdue'
        get 'broadcast'
        get 'check'
      end
    end

    match 'accounts' => 'accounts#index', :as => :accounts
    match 'accounts/update' => 'accounts#update', :as => :update_account, :via => :post
    root :to =>  'transactions#index'
  end

  root :to => 'home#index'
end

app/views/admin/shared/_sidebar.html.erb
<div class="page-header">
  <h1>Yonetim</h1>
</div>
<div style="margin-bottom: 13px">
  <%= link_to 'Yeni Borc Ekle', new_admin_transaction_path, :class => 'btn btn-primary' %>
  <br/>
</div>

<div style="padding: 8px 0;" class="well">
  <ul class="nav nav-list">
    <li <% if current_page?(:controller => 'admin/transactions') %>class="active" <% end %> ><%= link_to 'Alacaklarim', admin_transactions_path %></li>
    <li <% if current_page?(:controller => 'admin/transactions', :action => 'overdue') %>class="active" <% end %> ><%= link_to 'Vadesi Gecenler',overdue_admin_transactions_path  %></li>
    <li <% if current_page?(:controller => 'admin/transactions', :action => 'paid') %>class="active" <% end %> ><%= link_to 'Odenmis Borclar', paid_admin_transactions_path %></li>
  </ul>
</div>