config/routes.rb
Borcly::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  namespace :admin do
    resources :transactions do
      collection do
        get 'paid'
        get 'overdue'
        get 'broadcast'
        get 'check'
      end
    end

    match 'accounts' => 'accounts#index', :as => :accounts
    match 'accounts/update' => 'accounts#update', :as => :update_account, :via => :post
    root :to =>  'transactions#index'
  end

  root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Borcly</title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <!-- Le styles -->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <style>
      body {
          padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
  </style>

  <!-- Le fav and touch icons -->
  <link href="images/favicon.ico" rel="shortcut icon">
  <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
  <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
  <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="i-bar"></span>
        <span class="i-bar"></span>
        <span class="i-bar"></span>
      </a>
      <a href="/" class="brand">Borcly</a>

      <div class="container nav-collapse">

        <% if user_signed_in? %>
            <ul class="nav">
              <li <% if current_page?(admin_root_path) %>class="active" <% end %> ><%= link_to 'Yonetim Ekrani', admin_root_path %></li>
            </ul>
        <% end %>

        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <% if user_signed_in? %>
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <i class="icon-user icon-white"></i>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Hesap Ayarlari", admin_accounts_path %></li>
                  <li><%= link_to "Cikis", destroy_user_session_path %></li>
                </ul>
            <% else %>
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  Giris
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to image_tag('facebook_32.png', :style => 'vertical-align:middle') + 'Facebook', user_omniauth_authorize_path(:facebook) %></li>
                  <li><%= link_to image_tag('twitter_32.png', :style => 'vertical-align:middle') + 'Twitter', user_omniauth_authorize_path(:twitter), %></li>
                </ul>
            <% end %>

          </li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <% [:notice, :error, :alert].each do |level| %>
      <% unless flash[level].blank? %>
          <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <%= content_tag :p, flash[level] %>
          </div>
      <% end %>
  <% end %>

  <%= yield %>

  <hr>
  <footer class="footer">
    <p>&copy; Company 2012</p>
  </footer>

</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>